# Default values for livy-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # -- Image repository
  baseRepository: gcr.io/mapr-252711
  # -- Image Name
  imageName: livy-0.7.0
  # imageName: livy-0.7.0-2.4.7
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: "202301161621R-ezaf1046"
  # -- Image pull policy
  pullPolicy: Always

#default spark image for spark applications created with livy
deImage: spark-3.3.1:202301161621R
#for livy-0.7.0/spark-2.4.7
#deImage: spark-2.4.7:202301161621R

# -- Image pull secrets
imagePullSecrets:
  - name: imagepull

createDefaultPullSecret: false
defaultPullSecret: imagepull

# -- String to partially override `spark-operator.fullname` template (will maintain the release name)
nameOverride: ""

# -- String to override release name
fullnameOverride: ""

# -- restart policy
restartPolicy: "Always"

automountServiceAccountToken: true

#HPE tenant namespace info
tenantIsUnsecure: false

#HPE tenant namespace service account
serviceAccount:
  # Specifies whether a service account should be created
  # Default Service account is hpe-{{ ReleaseNamespace }}, which is created by Tenant operator.
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use. Please only use the tenant Service Account
  # This name is used only when create ServiceAccount option is set to true.
  name: ""

#Create RBAC for the Service Account
rbac:
  #RBAC is created only when this flag is true and ServiceAccount.create is also true
  create: false

podSecurityContext: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

#container ports
ports:
  sshPort: 22
  livyHttpPort: 8998
  livyInternalPortStart: 10000
  livyInternalPortEnd: 10010

# resources -- Pod resource requests and limits
resources:
  limits:
    cpu: 8000m
    memory: 8Gi
    ephemeral-storage: 30Gi
  requests:
    cpu: 2000m
    memory: 8Gi
    ephemeral-storage: 30Gi

#owner Reference
ownerReference:
  overRide: false
  ownerReferences: {}

sessionRecovery:
  ##supported sessionRecovery Kind: disabled, pvc
  kind: disabled
  ##use this option to configure volumeClaimTemplate for kind pvc
  pvcTemplate:
    metadata:
      name: livy-sessionstore
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

# Config map created by hive metastore. Used to connect livy with metastore
hiveSiteSource: ""

sparkHistoryServer:
  integrate: false
  pvcName: ""
  eventsDir: "maprfs:///apps/spark/sampletenant"

# Alpha feature
# Configure HTTPS for the Livy UI.
livySsl:
  enable: true
  # Leave the two following options blank to use tenant SSL Keystore.
  # Alternatively, to use a custom keystore, configure the following options and corresponding options in livy.conf.
  sslSecretName: ""
  secretMountPath: ""
  # sslSecretName: "livy-ssl-secret"
  # secretMountPath: /var/livy

# Alpha feature
# Data provided in "extraConfigs" will be added to configuration files through a K8S secret.
# Available files to configure: livy.conf, livy-client.conf and spark-defaults.conf.
extraConfigs:
  livy.conf: |
    # livy.keystore = /var/livy/ssl_keystore
    # livy.keystore.password = examplepass
    # livy.key-password = examplepass

istio:
  enable: false

# Add custom labels to livy server pod
customLabels:

# Available values: no | static | storageclass
creteStaticVolume: no
